/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_edimax_edilife_service_LifeService */

#ifndef _Included_com_edimax_edilife_service_LifeService
#define _Included_com_edimax_edilife_service_LifeService
#ifdef __cplusplus
extern "C" {
#endif
#undef com_edimax_edilife_service_LifeService_MODE_PRIVATE
#define com_edimax_edilife_service_LifeService_MODE_PRIVATE 0L
#undef com_edimax_edilife_service_LifeService_MODE_WORLD_READABLE
#define com_edimax_edilife_service_LifeService_MODE_WORLD_READABLE 1L
#undef com_edimax_edilife_service_LifeService_MODE_WORLD_WRITEABLE
#define com_edimax_edilife_service_LifeService_MODE_WORLD_WRITEABLE 2L
#undef com_edimax_edilife_service_LifeService_MODE_APPEND
#define com_edimax_edilife_service_LifeService_MODE_APPEND 32768L
#undef com_edimax_edilife_service_LifeService_MODE_MULTI_PROCESS
#define com_edimax_edilife_service_LifeService_MODE_MULTI_PROCESS 4L
#undef com_edimax_edilife_service_LifeService_BIND_AUTO_CREATE
#define com_edimax_edilife_service_LifeService_BIND_AUTO_CREATE 1L
#undef com_edimax_edilife_service_LifeService_BIND_DEBUG_UNBIND
#define com_edimax_edilife_service_LifeService_BIND_DEBUG_UNBIND 2L
#undef com_edimax_edilife_service_LifeService_BIND_NOT_FOREGROUND
#define com_edimax_edilife_service_LifeService_BIND_NOT_FOREGROUND 4L
#undef com_edimax_edilife_service_LifeService_BIND_ABOVE_CLIENT
#define com_edimax_edilife_service_LifeService_BIND_ABOVE_CLIENT 8L
#undef com_edimax_edilife_service_LifeService_BIND_ALLOW_OOM_MANAGEMENT
#define com_edimax_edilife_service_LifeService_BIND_ALLOW_OOM_MANAGEMENT 16L
#undef com_edimax_edilife_service_LifeService_BIND_WAIVE_PRIORITY
#define com_edimax_edilife_service_LifeService_BIND_WAIVE_PRIORITY 32L
#undef com_edimax_edilife_service_LifeService_BIND_IMPORTANT
#define com_edimax_edilife_service_LifeService_BIND_IMPORTANT 64L
#undef com_edimax_edilife_service_LifeService_BIND_ADJUST_WITH_ACTIVITY
#define com_edimax_edilife_service_LifeService_BIND_ADJUST_WITH_ACTIVITY 128L
#undef com_edimax_edilife_service_LifeService_CONTEXT_INCLUDE_CODE
#define com_edimax_edilife_service_LifeService_CONTEXT_INCLUDE_CODE 1L
#undef com_edimax_edilife_service_LifeService_CONTEXT_IGNORE_SECURITY
#define com_edimax_edilife_service_LifeService_CONTEXT_IGNORE_SECURITY 2L
#undef com_edimax_edilife_service_LifeService_CONTEXT_RESTRICTED
#define com_edimax_edilife_service_LifeService_CONTEXT_RESTRICTED 4L
#undef com_edimax_edilife_service_LifeService_START_CONTINUATION_MASK
#define com_edimax_edilife_service_LifeService_START_CONTINUATION_MASK 15L
#undef com_edimax_edilife_service_LifeService_START_STICKY_COMPATIBILITY
#define com_edimax_edilife_service_LifeService_START_STICKY_COMPATIBILITY 0L
#undef com_edimax_edilife_service_LifeService_START_STICKY
#define com_edimax_edilife_service_LifeService_START_STICKY 1L
#undef com_edimax_edilife_service_LifeService_START_NOT_STICKY
#define com_edimax_edilife_service_LifeService_START_NOT_STICKY 2L
#undef com_edimax_edilife_service_LifeService_START_REDELIVER_INTENT
#define com_edimax_edilife_service_LifeService_START_REDELIVER_INTENT 3L
#undef com_edimax_edilife_service_LifeService_START_FLAG_REDELIVERY
#define com_edimax_edilife_service_LifeService_START_FLAG_REDELIVERY 1L
#undef com_edimax_edilife_service_LifeService_START_FLAG_RETRY
#define com_edimax_edilife_service_LifeService_START_FLAG_RETRY 2L
/*
 * Class:     com_edimax_edilife_service_LifeService
 * Method:    init
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_edimax_edilife_service_LifeService_init
    (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     com_edimax_edilife_service_LifeService
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_edimax_edilife_service_LifeService_release
    (JNIEnv *, jobject);

/*
 * Class:     com_edimax_edilife_service_LifeService
 * Method:    customCGI
 * Signature: (Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_edimax_edilife_service_LifeService_customCGI
    (JNIEnv *, jobject, jstring, jint, jstring, jstring);

/*
 * Class:     com_edimax_edilife_service_LifeService
 * Method:    search
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_edimax_edilife_service_LifeService_search
    (JNIEnv *, jobject);

/*
 * Class:     com_edimax_edilife_service_LifeService
 * Method:    connect
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_edimax_edilife_service_LifeService_connect
    (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jint);

/*
 * Class:     com_edimax_edilife_service_LifeService
 * Method:    connectByIP
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_edimax_edilife_service_LifeService_connectByIP
    (JNIEnv *, jobject, jstring, jstring, jstring, jint);

/*
 * Class:     com_edimax_edilife_service_LifeService
 * Method:    disconnect
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_edimax_edilife_service_LifeService_disconnect
    (JNIEnv *, jobject, jstring);

/*
 * Class:     com_edimax_edilife_service_LifeService
 * Method:    login
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_edimax_edilife_service_LifeService_login
    (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     com_edimax_edilife_service_LifeService
 * Method:    getSnapshot
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_edimax_edilife_service_LifeService_getSnapshot
    (JNIEnv *, jobject, jstring);

/*
 * Class:     com_edimax_edilife_service_LifeService
 * Method:    startRTSP
 * Signature: (Ljava/lang/String;ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_edimax_edilife_service_LifeService_startRTSP
    (JNIEnv *, jobject, jstring, jint, jstring);

/*
 * Class:     com_edimax_edilife_service_LifeService
 * Method:    stopRTSP
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_edimax_edilife_service_LifeService_stopRTSP
    (JNIEnv *, jobject, jstring);

/*
 * Class:     com_edimax_edilife_service_LifeService
 * Method:    startSend_Audio
 * Signature: (Ljava/lang/String;[BIII)V
 */
JNIEXPORT void JNICALL Java_com_edimax_edilife_service_LifeService_startSend_1Audio
    (JNIEnv *, jobject, jstring, jbyteArray, jint, jint, jint);

/*
 * Class:     com_edimax_edilife_service_LifeService
 * Method:    sendAudio
 * Signature: (Ljava/lang/String;[BII)V
 */
JNIEXPORT void JNICALL Java_com_edimax_edilife_service_LifeService_sendAudio
    (JNIEnv *, jobject, jstring, jbyteArray, jint, jint);

/*
 * Class:     com_edimax_edilife_service_LifeService
 * Method:    stopSendAudio
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_edimax_edilife_service_LifeService_stopSendAudio
    (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_edimax_edilife_service_LifeService
 * Method:    panTilt
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_edimax_edilife_service_LifeService_panTilt
    (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     com_edimax_edilife_service_LifeService
 * Method:    getEventList
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_edimax_edilife_service_LifeService_getEventList
    (JNIEnv *, jobject, jstring);

/*
 * Class:     com_edimax_edilife_service_LifeService
 * Method:    getEventFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_edimax_edilife_service_LifeService_getEventFile
    (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_edimax_edilife_service_LifeService
 * Method:    startReadAVIFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_edimax_edilife_service_LifeService_startReadAVIFile
    (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_edimax_edilife_service_LifeService
 * Method:    stopReadAVIFile
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_edimax_edilife_service_LifeService_stopReadAVIFile
    (JNIEnv *, jobject);


/*
 * Class:     com_edimax_edilife_service_LifeService
 * Method:    getDBKeys
 * Signature: ([B[B)V
 */
JNIEXPORT void JNICALL Java_com_edimax_edilife_service_LifeService_getDBKeys
    (JNIEnv *, jobject, jbyteArray, jbyteArray);


#ifdef __cplusplus
}
#endif
#endif
